const express=require('express');
const router=express.Router();
const ratingController=require('../controllers/RatingController');
const { authenticateToken, requireClient }=require('../middlewares/auth');
const multer=require('multer');
const path=require('node:path');
const upload=multer({dest:path.join(__dirname,'../../uploads/temp/'),limits:{fileSize:50*1024*1024,files:10},fileFilter:(req,file,cb)=>cb(null,true)});
router.use(authenticateToken);
router.post('/:providerId/ratings',(req,res,next)=>{const m=upload.array('attachments',10);m(req,res,(err)=>{if(err){return res.status(400).json({success:false,message:'Erro ao processar arquivos: '+err.message});}next();});},requireClient,ratingController.create);
router.get('/:providerId/ratings',ratingController.index);
module.exports=router;
